export const MOVE_ROLLER_BLIND = 'MOVE_ROLLER_BLIND';
export const SET_ROLLER_BLIND_POSITION = 'server/SET_POSITION';

export const SET_POSITION = 'SET_POSITION';
export const SERVER_ERROR = 'SERVER_ERROR';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
